### ISSUE TITLE
generate_tradingeconomics_market_schema.py errors out

### ISSUE THREAD

**Issue by RqS** [usc-isi-i2/datamart#30]
Error message
```
Generating schema for Trading economics HYPE3:BS
Traceback (most recent call last):
  File "generate_tradingeconomics_market_schema.py", line 123, in <module>
    generate_json_schema(args.dst_path)
  File "generate_tradingeconomics_market_schema.py", line 48, in generate_json_schema
    data = res_indicator.json()
  File "/anaconda3/envs/datamart_env/lib/python3.6/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/anaconda3/envs/datamart_env/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/anaconda3/envs/datamart_env/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/anaconda3/envs/datamart_env/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by SukritiSharma** [comment]
I found the issue is because there are few paths which make invalid URL. 
This is the exhaustive list for the same. I have added try catch for now if we encounter invalid urls. Also contacted the support team of trading economics asking about the same.
Path
--
UU/:LN
ELEMENT*:MM
GIB/A:CN
BA/:LN
SN/:LN
RB/:LN
CMOCTEZ*:MM
ACO/X:CN
ATD/B:CN
ELEKTRA*:MM
GIGANTE*:MM
600420:CH
JE/:LN
DII/B:CN
HL/:LN
CTC/A:CN
AC*:MM
VESTA*:MM
ALSEA*:MM
TCL/A:CN
SJR/B:CN
HERDEZ*:MM
BT/A:LN
GENTERA*:MM
MEXCHEM*:MM
2810:JP
QBR/B:CN
CREAL*:MM
AV/:LN
RCI/B:CN
BBD/B:CN
BAM/A:CN
AEROMEX*:MM
IENOVA*:MM
Q*:MM
TW/:LN
GCC*:MM
HCITY*:MM
EMP/A:CN
CCL/B:CN
WALMEX*:MM
AGUA*:MM
PINFRA*:MM

**Comment by SukritiSharma** [comment]
Follow up from support team:
Hello Sukriti,
This symbols have some special characters that are not really URL friendly. I will look into them and get back to you.

Best regards,
Duarte Quintela

I think for now try catch is the best solution. Once I have a correct list I will update the csv.

**Comment by RqS** [comment]
Sounds good! Closing
