### ISSUE TITLE
wikitable dependencies/env 

### ISSUE THREAD

**Issue by Lituta** [usc-isi-i2/datamart#78]
When running unittest I met the following error
```
ERROR: test_get (datamart.unit_tests.test_wikitables_materializer.TestWikitablesMaterializer)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nas/home/dongyul/miniconda3/envs/datamart_env/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/nas/home/dongyul/miniconda3/envs/datamart_env/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/nas/home/dongyul/miniconda3/envs/datamart_env/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'geckodriver': 'geckodriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nas/home/dongyul/datamart_work/datamart/datamart/utilities/utils.py", line 156, in __decorator
    func(self)
  File "/nas/home/dongyul/datamart_work/datamart/datamart/unit_tests/test_wikitables_materializer.py", line 25, in test_get
    result = self.wikitables_materializer.get(metadata=mock_metadata).to_dict(orient="records")
  File "/nas/home/dongyul/datamart_work/datamart/datamart/materializers/wikitables_materializer.py", line 31, in get
    tab = tables(article=args['url'], lang=lang, store_result=False, xpath=args['xpath'])
  File "/nas/home/dongyul/datamart_work/datamart/datamart/materializers/wikitables_downloader/wikitables.py", line 43, in tables
    document = cache(get_with_render, (url, SELECTOR_ROOT), identifier=url)
  File "/nas/home/dongyul/datamart_work/datamart/datamart/materializers/wikitables_downloader/utils.py", line 163, in cache
    res = target(*args)
  File "/nas/home/dongyul/datamart_work/datamart/datamart/materializers/wikitables_downloader/utils.py", line 219, in get_with_render
    driver = get_driver(headless, disable_images, open_links_same_tab)
  File "/nas/home/dongyul/datamart_work/datamart/datamart/materializers/wikitables_downloader/utils.py", line 204, in get_driver
    _driver = Firefox(options=opts)
  File "/nas/home/dongyul/miniconda3/envs/datamart_env/lib/python3.6/site-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
    self.service.start()
  File "/nas/home/dongyul/miniconda3/envs/datamart_env/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.
```

after manually download `geckodriver` and specify the path, I met:
```
ERROR: test_get (datamart.unit_tests.test_wikitables_materializer.TestWikitablesMaterializer)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nas/home/dongyul/datamart_work/datamart/datamart/utilities/utils.py", line 156, in __decorator
    func(self)
  File "/nas/home/dongyul/datamart_work/datamart/datamart/unit_tests/test_wikitables_materializer.py", line 25, in test_get
    result = self.wikitables_materializer.get(metadata=mock_metadata).to_dict(orient="records")
  File "/nas/home/dongyul/datamart_work/datamart/datamart/materializers/wikitables_materializer.py", line 31, in get
    tab = tables(article=args['url'], lang=lang, store_result=False, xpath=args['xpath'])
  File "/nas/home/dongyul/datamart_work/datamart/datamart/materializers/wikitables_downloader/wikitables.py", line 43, in tables
    document = cache(get_with_render, (url, SELECTOR_ROOT), identifier=url)
  File "/nas/home/dongyul/datamart_work/datamart/datamart/materializers/wikitables_downloader/utils.py", line 163, in cache
    res = target(*args)
  File "/nas/home/dongyul/datamart_work/datamart/datamart/materializers/wikitables_downloader/utils.py", line 219, in get_with_render
    driver = get_driver(headless, disable_images, open_links_same_tab)
  File "/nas/home/dongyul/datamart_work/datamart/datamart/materializers/wikitables_downloader/utils.py", line 204, in get_driver
    _driver = Firefox(options=opts)
  File "/nas/home/dongyul/miniconda3/envs/datamart_env/lib/python3.6/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/nas/home/dongyul/miniconda3/envs/datamart_env/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/nas/home/dongyul/miniconda3/envs/datamart_env/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/nas/home/dongyul/miniconda3/envs/datamart_env/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/nas/home/dongyul/miniconda3/envs/datamart_env/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities
```

Both on Mac OS and CentOS 7

**Comment by Lituta** [comment]
Solved after `yum install firefox` on CentOS. is there a way to do the things automatically?
